### ISSUE TITLE
Unique combinations of different fields

### ISSUE THREAD

**Issue by smorken** [CWFC-CCFB/CFSStandGrowth4R#7]
Minor suggestion for usability: It might be useful to have a method to fetch the unique values/unique combinations of values for the fields, so that users can know what's available to query, without querying the entire dataset.  I couldn't spot any easy way to do this in the available functionality, so sorry if I missed it.

> fields
 [1] "mmid"                "geoDomain"           "dataSource"          "nbRealizations"      "climateChangeOption" "growthModel"         "timeStamp"          
 [8] "outputType"          "fitModel"            "stratumGroup" 
 
 something like:
 
 ```R
 # get a table of the unique combinations of "geoDomain", "dataSource" that are available
 CFSStandGrowth4R::SGGetMetaModelFieldValues("geoDomain", "dataSource")
 ```

**Comment by donenrique24** [comment]
Sorry for the late reply: I forgot to add a watch on the project and I just noticed you posted this issue. 
Thanks for your comment. 
That is a good idea. I'll keep you posted as soon as this is done. 
Mathieu

**Comment by donenrique24** [comment]
A new function called SGGetMetaModelFieldCombinations has been added to the package.
